### ISSUE TITLE
Building a WebGL-enabled printing backend with Electron

### ISSUE THREAD

**Issue by danmactough** [NodeDC/organizers#36]
# Building a WebGL-enabled printing backend with Electron

Yeah, it's 2016, but our customers still need to print -- you know, on paper. Yet most of our app is rendered with WebGL, which presents some challenges. Naturally, we chose to solve those problems by writing a headless Electron app. This talk will cover the problems presented, the possible solutions we considered, and the problems encountered with our chosen solution.
- Not browser-based: My content is centered around JavaScript executing outside of a web browser.
- I will be in Washington, DC while presenting.
## Prerequisites

No prerequisite knowledge is required.

**Comment by JuanCaicedo** [comment]
Gee, I know _someone_ who had that exact problem ;)

This sounds really interesting! I'm not sure I would agree that no prereq knowledge is required, it actually sounds pretty advanced to me, but I guess it depends on how the speaker presents it. I would want to be sure we chat with the speaker so that the scope of it isn't too big. I would definitely want to see it though!

**Comment by danpaz** [comment]
This topic goes way over my head, so I definitely want to hear more about it!

**Comment by joshfinnie** [comment]
Yeah, I don't know what `Electron` is... might be a worthy prerequisite ;-)
