### ISSUE TITLE
Server rendering your single page app with React.js for better UX

### ISSUE THREAD

**Issue by danmactough** [NodeDC/organizers#46]
Presented by @d6u via NodeDC/talks#3

Scheduled for 6/16

**Comment by danmactough** [comment]
@d6u As you know, we got our scheduled date stomped on. What are some options for rescheduling that work for you?

**Comment by jakerella** [comment]
Aaaaw... I wouldn't say stomped on! I swear, I checked the schedules of the local JS-ish meetups and no one had anything that day, also, NodeDC's regular meetup day appeared to be the third Thursday! I would not have scheduled the DCJS meetup that day if I had known.

**Comment by danmactough** [comment]
@jakerella that is the 3rd thursday. don't worry about it though. shit happens.

**Comment by d6u** [comment]
@danmactough @jakerella I'm totally fine 🌞 

I really can do anytime you guys want. One idea I have is since this related to both frontend JS, Node.js and React.js, I will be OK if we want to do a joint event with ReactDC or DCJS. I will leave it up to you guys to decide. But again, any Tuesday to Thursday works for me as long as it's after June 16. Thanks a lot.

**Comment by JuanCaicedo** [comment]
We had talked about doing a week later on June 23, I think that works for everyone

**Comment by danmactough** [comment]
cool. since 6/23 works for @d6u I'll check on availability

**Comment by danmactough** [comment]
nope. 😭 How about 6/30?

**Comment by d6u** [comment]
@danmactough SGTM ;)

**Comment by danmactough** [comment]
ok. we're all set for 6/30.

**Comment by danmactough** [comment]
talk was great!
